### ISSUE TITLE
BASE_URL_NUTS_NODE should be read from environment variables

### ISSUE THREAD

**Issue by reinkrul** [jorritspee/lspxnuts-proxyserver#1]
Maybe with the specified default.

**Comment by jorritspee** [comment]
Hi Rein, you are absolutely right. I will try and rewrite the little codebase we have to use the Flask framework. It looks a lot cleaner and brings a lot of functionality for free. https://pypi.org/project/Flask/

**Comment by jorritspee** [comment]
For config stuff, this looks pretty cool: https://python.land/data-processing/python-yaml#Reading_and_parsing_a_YAML_file_with_Python

**Comment by jorritspee** [comment]
BASE_URL_NUTS_NODE and other config stuff can now be set in config.json.
